### ISSUE TITLE
/postcalendar does nothing

### ISSUE THREAD

**Issue by MsLusica** [dit-calendar/teamup-telegram-bot#12]
Hey, 
I am new to the telegram-bot stuff.
I thoroughly followed your instructions but calling </postcalendar name date> has no effect. 
What do I do wrong?
Thanks for your help.
MsLusica

**Comment by boddAH23** [comment]
Hi @MsLusica,
does the bot answer on any other command like `/help`? Can you see any errors in your logs? If you deploy with heroku you can access logs through https://dashboard.heroku.com/apps/{yourAppName}/logs
Sometimes you need to restart your app to see logs, if you have not used your app for a while. You can restart your app under the "More"-button
![heroku](https://user-images.githubusercontent.com/5122557/117289702-3348a800-ae6d-11eb-96b5-9560b246c6e7.png)

**Comment by MsLusica** [comment]
Hey @boddAH23, 
thanks for your reply. 
I did the whole build again and it works now!
Thanks a lot. 
MsLusica

**Comment by vitaB** [comment]
Ok, cool. I will close the ticket then.

Just for your information:
You can always check the bot status on https://api.telegram.org/bot{telegramtoken}/getWebhookInfo

Which should respond with:

`{"ok":true,"result":{"url":"https://{app-name}.herokuapp.com/{telegramtoken}","has_custom_certificate":false,"pending_update_count":0,"max_connections":40,"ip_address":"54.246.237.57"}}`


And if you invite your bot into a group or channel, you have to keep in mind that it needs permissions to send messages, like any other telegram-user.

Btw. the command /help is disabled in channels.
