### ISSUE TITLE
Is it possible to post the whole calendar?

### ISSUE THREAD

**Issue by allakutkina** [dit-calendar/teamup-telegram-bot#9]
As far as I understood now the bot gives only sub-calendar data. Is it possible to implement an option to post the whole thing?

Thank you for your project!

**Comment by vitaB** [comment]
Hey thanks for the suggestion. Do you mean that in the case where no subcalendar name is specified (first paramenter would be the date), all subcalendars should be posted?
![grafik](https://user-images.githubusercontent.com/5122557/105077371-ba276f80-5a8c-11eb-85ae-39471bad5a8e.png)
We have assumed that posting all subcalendars would make the telegram message a bit overwhelming. We would probably need some kind of separators within the message. Or the telegram bot could post a separate message for each subcalendar.

**Comment by allakutkina** [comment]
Yes I meant something like this, in my case I have 6 sub calendars and each has only one or two events, so would be great to have the whole calendar in one maybe longer message.
Thanks for the fast reply and your effort ✨

**Comment by boddAH23** [comment]
We have implemented this in a way that each calendar is posted in a separate message. This feature is disabled by default and can be enabled through: `post.calendar.without.subcalendar.name=true` 

@allakutkina would be nice if you could test this
